[build]
  command = "npm ci && npm run build"
  publish = "dist/invitacion-carlos"

[build.environment]
  NODE_VERSION = "20"

# SPA: redirige todas las rutas a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
